# GitHub Actions CI: run pytest across supported operating systems and Python versions
name: CI

on:
  push:
    branches: [ main, master, '**/test/**', '**/ci/**' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: pytest (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            pytest.ini

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install -e .[dev]
          fi

      - name: Run tests with pytest
        env:
          PYTHONWARNINGS: default
        run: pytest

      - name: Upload coverage XML as artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}-${{ matrix.os }}
          path: coverage.xml

      - name: (Optional) Upload coverage to Codecov
        if: runner.os == 'Linux' && secrets.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
